SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Железные дороги', NULL, 500)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Железнодорожный транспорт', 500, 501)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Ж.д. станции АМКР', 500, 502)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Ж.д. станции АМКР с выходом на УЗ', 502, 503)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Станционные пути', 500, 504)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Перегоны', 500, 505)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Пути ПТО', 500, 506)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Пути с гаражами размораживания', 500, 507)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Пути очистки вагонов', 500, 508)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Тупики разгрузки', 500, 509)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Тупики загрузки', 500, 510)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Ж.д. транспорт АМКР', 501, 511)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Ж.д. транспорт внешних владельцев', 501, 512)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Локомотивы', 501, 513)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Вагоны', 501, 514)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Цистерны', 514, 515)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Цистерны для перевозки бензола', 514, 516)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Цистерны для перевозки смолы', 514, 517)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Цистерны для перевозки сульфата', 514, 518)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Полувагоны', 514, 519)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Полувагоны с крышей', 519, 520)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Полувагоны открытые', 519, 521)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Полувагоны шадринской конструкции', 519, 522)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Хопперы', 514, 523)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Коксовозы', 523, 524)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Цементовозы', 523, 525)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Аглохопперы', 523, 526)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Окатышевозы', 523, 527)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Платформы', 514, 528)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Ленточные платформы', 528, 529)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Обрезные платформы', 528, 530)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Металлошихтовые платформы', 528, 531)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Скрапные платформы', 528, 532)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Платформы под заготовку', 528, 533)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Плптформы универсальные', 528, 534)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Думкары', 514, 535)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Думкары под муссор', 535, 536)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Думкары под граншлак', 535, 537)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Думкары под металлолом', 535, 538)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Спец-подвижной состав', 514, 539)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Чугуновозы', 539, 540)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Шлаковозы', 539, 541)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Изложницы', 539, 542)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Ракеты для металлолома', 539, 543)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Тепловозы', 513, 544)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'ТЭМ', 544, 545)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'ТГМ', 544, 546)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Ж.д. станции АМКР без выхода на УЗ', 502, 547)
INSERT INTO [dbo].[PhysicalAssetClass]  ([Description],[ParentID] ,[ID]) VALUES (N'Ж.д. станции внешних дорог', 501, 548)
GO

