USE [KRR-PA-ISA95_PRODUCTION]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

IF OBJECT_ID ('AMKR_WEIGHING.KP4_WagonNumberRecognition',N'U') IS NOT NULL
  DROP TABLE [AMKR_WEIGHING].[KP4_WagonNumberRecognition];
GO

CREATE TABLE [AMKR_WEIGHING].[KP4_WagonNumberRecognition](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DT] [datetime] NULL DEFAULT (getdate()),
	[WagonNumber] [nvarchar](8) NULL,
	[Quality] [float] NULL,
 CONSTRAINT [PK_KP4_WagonNumberRecognition] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


GO