USE [KRR-PA-ISA95_PRODUCTION]
GO


if SCHEMA_ID ( 'ISA95_MATERIAL' ) IS NULL
	exec('CREATE SCHEMA ISA95_MATERIAL')
go	

	
if SCHEMA_ID ( 'ISA95_PHYSICAL_ASSET' ) IS NULL
	exec('CREATE SCHEMA ISA95_PHYSICAL_ASSET')
go


if SCHEMA_ID ( 'ISA95_EQUIPMENT' ) IS NULL
	exec('CREATE SCHEMA ISA95_EQUIPMENT')
go


if SCHEMA_ID ( 'ISA95EXT_PACKAGING' ) IS NULL
	exec('CREATE SCHEMA ISA95EXT_PACKAGING')
go


if SCHEMA_ID ( 'ISA95EXT_LOCATION' ) IS NULL
	exec('CREATE SCHEMA ISA95EXT_LOCATION')
go


if SCHEMA_ID ( 'ISA95_OPERATION_DEFINITION' ) IS NULL
	exec('CREATE SCHEMA ISA95_OPERATION_DEFINITION')
go


if SCHEMA_ID ( 'ISA95_WORK_DEFINITION' ) IS NULL
	exec('CREATE SCHEMA ISA95_WORK_DEFINITION')
go


if SCHEMA_ID ( 'ISA95_OPERATION_SCHEDULE' ) IS NULL
	exec('CREATE SCHEMA ISA95_OPERATION_SCHEDULE')
go


if SCHEMA_ID ( 'ISA95_WORK_SCHEDULE' ) IS NULL
	exec('CREATE SCHEMA ISA95_WORK_SCHEDULE')
go


if SCHEMA_ID ( 'ISA95_OPERATION_PERFORMANCE' ) IS NULL
	exec('CREATE SCHEMA ISA95_OPERATION_PERFORMANCE')
go


if SCHEMA_ID ( 'ISA95_WORK_PERFORMANCE' ) IS NULL
	exec('CREATE SCHEMA ISA95_WORK_PERFORMANCE')
go


if SCHEMA_ID ( 'AMKR_ROLLING_LABEL_PRINT' ) IS NULL
	exec('CREATE SCHEMA AMKR_ROLLING_LABEL_PRINT')
go


if SCHEMA_ID ( 'AMKR_WEIGHING' ) IS NULL
	exec('CREATE SCHEMA AMKR_WEIGHING')
go


if SCHEMA_ID ( 'AMKR_OXYGEN_ACCOUNTING' ) IS NULL
	exec('CREATE SCHEMA AMKR_OXYGEN_ACCOUNTING')
go


if SCHEMA_ID ( 'AMKR_TRANSPORT' ) IS NULL
	exec('CREATE SCHEMA AMKR_TRANSPORT')
go


if SCHEMA_ID ( 'AML' ) IS NULL
	exec('CREATE SCHEMA AML')
go


if SCHEMA_ID ( 'MIMOSA' ) IS NULL
	exec('CREATE SCHEMA MIMOSA')
go
