SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID ('dbo.InsKeplogger',N'TR') IS NOT NULL
   DROP TRIGGER [dbo].[InsKeplogger];
GO

if OBJECT_ID ('dbo.KEP_logger',N'U') IS NOT NULL
   DROP table [dbo].[KEP_logger];
GO

CREATE TABLE [dbo].[KEP_logger](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[AUTO_MANU] [bit] NULL,
	[COUNT_BAR] [int] NULL,
	[NUMBER_POCKET] [int] NULL,
	[POCKET_LOC] [bit] NULL,
	[REM_BAR] [int] NULL,
	[WEIGHT_CURRENT] [real] NULL,
	[TIMESTAMP] [datetime] NULL,
	[WEIGHT_FIX] [int] NULL,
	[WEIGHT_OK] [bit] NULL,
	[WEIGHT_SP_MAX] [real] NULL,
	[WEIGHT_SP_MIN] [real] NULL,
	[WEIGHT_STAB] [bit] NULL,
	[WEIGHT_ZERO] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX [i1_kep_logger_timestamp] ON [dbo].[KEP_logger]
(
	[TIMESTAMP] ASC,
	[NUMBER_POCKET] ASC
)
INCLUDE ([WEIGHT_CURRENT]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]
GO


