CREATE TABLE OperationsClass (
	ID INT NOT NULL,
	ParentID INT NULL,
	DESCRIPTION NVARCHAR(50) NOT NULL
CONSTRAINT PK_OperationsClass PRIMARY KEY CLUSTERED (ID) 
	WITH (PAD_INDEX=OFF, STATISTICS_NORECOMPUTE = OFF,IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
ON [PRIMARY]
) 
ON [PRIMARY]
GO

ALTER TABLE OperationsClass  
WITH CHECK ADD CONSTRAINT FK_OperationsClassID_OperationsClassParentID FOREIGN KEY(ParentID)
REFERENCES OperationsClass (ID)
GO

CREATE TABLE WorkClass (
	ID INT NOT NULL,
	ParentID INT NULL,
	OperationsClassID INT NOT NULL,
	DESCRIPTION NVARCHAR(50) NOT NULL
CONSTRAINT PK_WorkClass PRIMARY KEY CLUSTERED (ID) 
	WITH (PAD_INDEX=OFF, STATISTICS_NORECOMPUTE = OFF,IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
ON [PRIMARY]
) 
ON [PRIMARY]
GO

ALTER TABLE WorkClass
WITH CHECK ADD CONSTRAINT FK_WorkClassID_WorkClassParentID FOREIGN KEY(ParentID)
REFERENCES WorkClass (ID)
GO

ALTER TABLE WorkClass
WITH CHECK ADD CONSTRAINT FK_OperationsClassID_WorkClassID FOREIGN KEY(OperationsClassID)
REFERENCES OperationsClass (ID)
GO

ALTER TABLE OperationsClass
ADD
	OperationsClassID INT NULL
	CONSTRAINT FK_OperationsClass_OperationsDefinition FOREIGN KEY (OperationsClassID)
	REFERENCES OperationsClass (ID)
GO 

ALTER TABLE WorkDefinition
ADD
	WorkClassID INT NULL
	CONSTRAINT FK_WorkClass_WorkDefinition FOREIGN KEY (WorkClassID)
	REFERENCES WorkClass (ID)
GO 
