DECLARE @WorkShopEquipmentClassID INT,
        @MillEquipmentClassID INT,
        @SideEquipmentClassID INT,
        @PrinterEquipmentClassID INT,
        @ScalesEquipmentClassID INT,
        @WorkShopEquipmentID INT,
        @MillEquipmentID INT,
        @SideEquipmentID INT,
        @ScaleEquipmentID INT,
        @PrinterEquipmentID INT;

SELECT @MillEquipmentClassID=[ID] FROM [dbo].[EquipmentClass] WHERE [Code]=N'MILL';
SELECT @SideEquipmentClassID=[ID] FROM [dbo].[EquipmentClass] WHERE [Code]=N'SIDE';
SELECT @WorkShopEquipmentClassID=[ID] FROM [dbo].[EquipmentClass] WHERE [Code]=N'WORKSHOP';
SELECT @PrinterEquipmentClassID=[ID] FROM [dbo].[EquipmentClass] WHERE [Code]=N'PRINTER';
SELECT @ScalesEquipmentClassID=[ID] FROM [dbo].[EquipmentClass] WHERE [Code]=N'SCALES';

BEGIN TRANSACTION;

delete from EquipmentProperty where EquipmentID<29;
delete from EquipmentRequirement where EquipmentID<29;
delete from Equipment where ID<29;

--Блюминг АБК СГП
SET @WorkShopEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@WorkShopEquipmentID,N'Блюминг АБК СГП',NULL,@WorkShopEquipmentClassID);
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер Блюминга 2',@WorkShopEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'1',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Весы',@WorkShopEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Ручные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'15',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));

--СПЦ-1
SET @WorkShopEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@WorkShopEquipmentID,N'СПЦ-1',NULL,@WorkShopEquipmentClassID);
SET @MillEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@MillEquipmentID,N'ПС 150-1',@WorkShopEquipmentID,@MillEquipmentClassID);
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер ПС 150-1',@MillEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'2',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Бунтовые',@MillEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Бунтовые',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'16',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'0',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'ENTERED',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PACK_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'4',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PACK_WEIGHT'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @MillEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@MillEquipmentID,N'МС 250-1',@WorkShopEquipmentID,@MillEquipmentClassID);
SET @SideEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@SideEquipmentID,N'Левая',@MillEquipmentID,@SideEquipmentClassID);
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер МС 250-1 левая',@SideEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'3',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'ZDesigner 140Xi4 203 dpi',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NAME'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 1',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'17',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'11',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'CONTROLLER_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 2',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'18',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'12',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'CONTROLLER_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 3',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'19',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'13',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'CONTROLLER_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 4',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'20',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'14',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'CONTROLLER_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @SideEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@SideEquipmentID,N'Правая',@MillEquipmentID,@SideEquipmentClassID);
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер МС 250-1 правая',@SideEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'4',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 1',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'21',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'21',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'CONTROLLER_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 2',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'22',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'22',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'CONTROLLER_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 3',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'23',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'23',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'CONTROLLER_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 4',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'24',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'24',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'CONTROLLER_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @MillEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@MillEquipmentID,N'МС 250-2',@WorkShopEquipmentID,@MillEquipmentClassID);
SET @SideEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@SideEquipmentID,N'Левая',@MillEquipmentID,@SideEquipmentClassID);
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер МС 250-2 левая',@SideEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 1',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'25',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 2',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'26',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Упаковка',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Весы линии упаковки',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'27',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @SideEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@SideEquipmentID,N'Правая',@MillEquipmentID,@SideEquipmentClassID);
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 1',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'28',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 2',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'29',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер МС 250-2 правая',@SideEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'6',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Упаковка',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Весы линии упаковки',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'30',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @MillEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@MillEquipmentID,N'МС 250-3',@WorkShopEquipmentID,@MillEquipmentClassID);
SET @SideEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@SideEquipmentID,N'Левая',@MillEquipmentID,@SideEquipmentClassID);
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер МС 250-3 левая',@SideEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'7',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Упаковка',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Весы линии упаковки',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'31',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 1',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'32',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 2',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'33',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 3',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'34',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @SideEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@SideEquipmentID,N'Правая',@MillEquipmentID,@SideEquipmentClassID);
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер МС 250-3 правая',@SideEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'8',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Упаковка',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Весы линии упаковки',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'35',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 1',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'36',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 2',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'37',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 3',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'38',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));

--СПЦ-2
SET @WorkShopEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@WorkShopEquipmentID,N'СПЦ-2',NULL,@WorkShopEquipmentClassID);
SET @MillEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@MillEquipmentID,N'МС 250-4',@WorkShopEquipmentID,@MillEquipmentClassID);
SET @SideEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@SideEquipmentID,N'Левая',@MillEquipmentID,@SideEquipmentClassID);
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер МС 250-4 левая',@SideEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'9',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 1',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'39',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'10',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 2',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'40',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'10',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 3',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'41',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'10',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @SideEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@SideEquipmentID,N'Правая',@MillEquipmentID,@SideEquipmentClassID);
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер МС 250-4 правая',@SideEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'10',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 1',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'42',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'10',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 2',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'43',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'10',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 3',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'44',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'10',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @MillEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@MillEquipmentID,N'МС 250-5',@WorkShopEquipmentID,@MillEquipmentClassID);
SET @SideEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@SideEquipmentID,N'Левая',@MillEquipmentID,@SideEquipmentClassID);
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер МС 250-5 левая',@SideEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'11',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 1',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'45',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 2',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'46',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 3',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'47',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Упаковка',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Весы линии упаковки',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'48',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @SideEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@SideEquipmentID,N'Правая',@MillEquipmentID,@SideEquipmentClassID);
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер МС 250-5 правая',@SideEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'12',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 1',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'49',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 2',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'50',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Карман 3',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Карманные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'51',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Упаковка',@SideEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Весы линии упаковки',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'52',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));

--ПЦ-3
SET @WorkShopEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@WorkShopEquipmentID,N'ПЦ-3',NULL,@WorkShopEquipmentClassID);
SET @MillEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@MillEquipmentID,N'ПС 6 (ПУ 8)',@WorkShopEquipmentID,@MillEquipmentClassID);
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер ПС 150-6',@MillEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'13',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Бунтовые',@MillEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Бунтовые',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'53',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'0',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'CALC',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PACK_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));

--ЦПМ
SET @WorkShopEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@WorkShopEquipmentID,N'ЦПМ',NULL,@WorkShopEquipmentClassID);
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер ЦПМП',@WorkShopEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'14',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Весы 1',@WorkShopEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Ручные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'55',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Весы 2',@WorkShopEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Ручные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'56',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Весы, линия гибки',@WorkShopEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Ручные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'57',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер холодного волочения',@WorkShopEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'15',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Весы, холодного волочения',@WorkShopEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Ручные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'58',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'UP',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));

--Блюминг 1 АБК комната мастеров
SET @WorkShopEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@WorkShopEquipmentID,N'Блюминг 1 АБК комната мастеров',NULL,@WorkShopEquipmentClassID);
SET @PrinterEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@PrinterEquipmentID,N'Принтер Блюминга 1',@WorkShopEquipmentID,@PrinterEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'16',@PrinterEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NO'));
SET @ScaleEquipmentID=NEXT VALUE FOR dbo.gen_Equipment;
INSERT INTO [dbo].[Equipment] ([ID],[Description],[Equipment],[EquipmentClassID]) VALUES (@ScaleEquipmentID,N'Весы',@WorkShopEquipmentID,@ScalesEquipmentClassID);
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'Ручные',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_TYPE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'15',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'SCALES_NO'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'5',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_PRECISION'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (N'DOWN',@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'ROUND_RULE'));
INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) VALUES (CAST(@PrinterEquipmentID AS NVARCHAR),@ScaleEquipmentID,dbo.get_EquipmentClassPropertyByValue(N'USED_PRINTER'));


INSERT INTO [dbo].[EquipmentProperty]([Value],[EquipmentID],[ClassPropertyID]) 
select N'Bullzip PDF Printer',ID,dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NAME') from Equipment where EquipmentClassID=@PrinterEquipmentClassID and ID not in (select EquipmentID from EquipmentProperty where ClassPropertyID=dbo.get_EquipmentClassPropertyByValue(N'PRINTER_NAME'));


COMMIT;
GO
