-- Structure 'DataType1Type' to define field UnitID
use [KRR-PA-ISA95_PRODUCTION]

SET IDENTITY_INSERT [dbo].[Unit] ON
GO
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (1,N'Amount')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (2,N'BinaryObject')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (3,N'Code')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (4,N'DateTime')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (5,N'Identifier')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (6,N'Indicator')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (7,N'Measure')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (8,N'Numeric')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (9,N'Quantity')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (10,N'Text')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (11,N'string')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (12,N'byte')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (13,N'unsignedByte')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (14,N'binary')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (15,N'integer')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (16,N'positiveInteger')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (17,N'negativeInteger')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (18,N'nonNegativeInteger')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (19,N'nonPositiveInteger')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (20,N'int')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (21,N'unsignedInt')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (22,N'long')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (23,N'unsignedLong')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (24,N'short')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (25,N'unsignedShort')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (26,N'decimal')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (27,N'float')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (28,N'double')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (29,N'boolean')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (30,N'time')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (31,N'timeInstant')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (32,N'timePeriod')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (33,N'duration')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (34,N'date')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (35,N'dateTime')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (36,N'month')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (37,N'year')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (38,N'century')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (39,N'recurringDay')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (40,N'recurringDate')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (41,N'recurringDuration')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (42,N'Name')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (43,N'QName')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (44,N'NCName')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (45,N'uriReference')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (46,N'language')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (47,N'ID')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (48,N'IDREF')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (49,N'IDREFS')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (50,N'ENTITY')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (51,N'ENTITIES')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (52,N'NOTATION')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (53,N'NMTOKEN')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (54,N'NMTOKENS')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (55,N'Enumeration')
INSERT INTO [dbo].[Unit]([ID],[Description]) VALUES (56,N'SVG')
SET IDENTITY_INSERT [dbo].[Unit] OFF
GO