--- Project gasCollection, Agbor
--- Insert data to table
SET NOCOUNT ON

INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10000, N'Диапазон', '-50..100 С', NULL, NULL, 10014);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10001, N'Длина погружной части', '250', NULL, NULL, 10014);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10002, N'Выходной сигнал', 'Pt100', NULL, NULL, 10014);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10003, N'Диапазон', '-50..150 С', NULL, NULL, 10015);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10004, N'Длина погружной части', '160', NULL, NULL, 10015);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10005, N'Выходной сигнал', '4-20 мА', NULL, NULL, 10015);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10006, N'Диапазон', '-50..150 С', NULL, NULL, 10016);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10007, N'Длина погружной части', '310', NULL, NULL, 10016);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10008, N'Выходной сигнал', '4-20 мА', NULL, NULL, 10016);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10009, N'Диапазон', '-50..100 С', NULL, NULL, 10017);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10010, N'Длина погружной части', '400', NULL, NULL, 10017);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10011, N'Выходной сигнал', '4-20 мА', NULL, NULL, 10017);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10012, N'Диапазон', '10 кПа', NULL, NULL, 10021);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10013, N'Выходной сигнал', '4-20 мА, HART', NULL, NULL, 10021);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10014, N'Диапазон', '50 кПа', NULL, NULL, 10022);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10015, N'Выходной сигнал', '4-20 мА, HART', NULL, NULL, 10022);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10016, N'Диапазон', '3 кПа', NULL, NULL, 10023);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10017, N'Выходной сигнал', '4-20 мА, HART', NULL, NULL, 10023);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10018, N'Диапазон', '10 кПа', NULL, NULL, 10024);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10019, N'Выходной сигнал', '4-20 мА, HART', NULL, NULL, 10024);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10020, N'Диапазон', '50 кПа', NULL, NULL, 10025);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10021, N'Выходной сигнал', '4-20 мА, HART', NULL, NULL, 10025);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10022, N'Грубина погружения датчика', '606', NULL, NULL, 10029);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10023, N'Выходной сигнал', '4-20 мА', NULL, NULL, 10029);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10024, N'Грубина погружения датчика', '435', NULL, NULL, 10030);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10025, N'Выходной сигнал', '4-20 мА', NULL, NULL, 10030);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10026, N'Диапазон', '4 МПа', NULL, NULL, 10007);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10027, N'Выходной сигнал', '4-20 мА, HART', NULL, NULL, 10007);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10028, N'Исполнение', 'Стандартное', NULL, NULL, 10007);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10029, N'Диапазон', '1 МПа', NULL, NULL, 10008);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10030, N'Выходной сигнал', '4-20 мА, HART', NULL, NULL, 10008);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10031, N'Исполнение', 'Стандартное', NULL, NULL, 10008);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10032, N'Диапазон', '200 кПа', NULL, NULL, 10009);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10033, N'Выходной сигнал', '4-20 мА, HART', NULL, NULL, 10009);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10034, N'Исполнение', 'Кислородное', NULL, NULL, 10009);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10035, N'Диапазон', '25 кПа', NULL, NULL, 10004);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10036, N'Выходной сигнал', '4-20 мА, HART', NULL, NULL, 10004);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10037, N'Исполнение', 'Кислородное', NULL, NULL, 10004);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10038, N'Диапазон', '4 МПа', NULL, NULL, 10010);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10039, N'Выходной сигнал', '4-20 мА, HART', NULL, NULL, 10010);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10040, N'Исполнение', 'Кислородное', NULL, NULL, 10010);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10041, N'Диапазон', '4 МПа', NULL, NULL, 10011);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10042, N'Диапазон', '4-20 мА, HART', NULL, NULL, 10011);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10043, N'Исполнение', 'Кислородное', NULL, NULL, 10011);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10044, N'Исполнение', 'Стандартное', NULL, NULL, 10021);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10045, N'Исполнение', 'Кислородное', NULL, NULL, 10022);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10046, N'Исполнение', 'Кислородное', NULL, NULL, 10023);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10047, N'Исполнение', 'Кислородное', NULL, NULL, 10024);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10048, N'Исполнение', 'Кислородное', NULL, NULL, 10025);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10049, N'Диапазон', '0-1%', NULL, NULL, 10033);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10050, N'Выходной сигнал', '4-20 мА, RS485 (ModBus)', NULL, NULL, 10033);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10051, N'Диапазон', '0-5%', NULL, NULL, 10034);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10052, N'Выходной сигнал', '4-20 мА, RS485 (ModBus)', NULL, NULL, 10034);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10053, N'Диапазон', '50-100%', NULL, NULL, 10035);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10054, N'Выходной сигнал', '4-20 мА, RS485 (ModBus)', NULL, NULL, 10035);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10055, N'Диапазон', '0-50%', NULL, NULL, 10036);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10056, N'Выходной сигнал', '4-20 мА, RS485 (ModBus)', NULL, NULL, 10036);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10057, N'Диапазон', '95-100%', NULL, NULL, 10037);
INSERT INTO [dbo].[PhysicalAssetClassProperty](ID, Description, Value, PhysicalAssetClassProperty, PhysicalAssetCapabilityTestSpecification, PhysicalAssetClassID) VALUES (10058, N'Выходной сигнал', '4-20 мА, RS485 (ModBus)', NULL, NULL, 10037);

GO
