
CREATE TABLE [dbo].[MIMEType](
	[ID]  [int] identity(1,1) NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[MIMEType] [nvarchar](255) NOT NULL,
	[Extension] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MIMETypes] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO



/****** Object:  Index [u_MIMEType]    Script Date: 13.05.2016 9:52:39 ******/
CREATE UNIQUE NONCLUSTERED INDEX [u_MIMEType] ON [dbo].[MIMEType]
(
	[Extension] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO




INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('3D Crossword Plugin', 'application/vnd.hzn-3d-crossword', '.x3d');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('3GP', 'video/3gpp', '.3gp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('3GP2', 'video/3gpp2', '.3g2');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('3GPP MSEQ File', 'application/vnd.mseq', '.mseq');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('3M Post It Notes', 'application/vnd.3m.post-it-notes', '.pwn');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('3rd Generation Partnership Project - Pic Large', 'application/vnd.3gpp.pic-bw-large', '.plb');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('3rd Generation Partnership Project - Pic Small', 'application/vnd.3gpp.pic-bw-small', '.psb');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('3rd Generation Partnership Project - Pic Var', 'application/vnd.3gpp.pic-bw-var', '.pvb');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('3rd Generation Partnership Project - Transaction Capabilities Application Part', 'application/vnd.3gpp2.tcap', '.tcap');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('7-Zip', 'application/x-7z-compressed', '.7z');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('AbiWord', 'application/x-abiword', '.abw');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Ace Archive', 'application/x-ace-compressed', '.ace');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Active Content Compression', 'application/vnd.americandynamics.acc', '.acc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('ACU Cobol', 'application/vnd.acucobol', '.acu');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('ACU Cobol', 'application/vnd.acucorp', '.atc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Adaptive differential pulse-code modulation', 'audio/adpcm', '.adp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Adobe (Macropedia) Authorware - Binary File', 'application/x-authorware-bin', '.aab');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Adobe (Macropedia) Authorware - Map', 'application/x-authorware-map', '.aam');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Adobe (Macropedia) Authorware - Segment File', 'application/x-authorware-seg', '.aas');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Adobe AIR Application', 'application/vnd.adobe.air-application-installer-package+zip', '.air');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Adobe Flash', 'application/x-shockwave-flash', '.swf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Adobe Flex Project', 'application/vnd.adobe.fxp', '.fxp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Adobe Portable Document Format', 'application/pdf', '.pdf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Adobe PostScript Printer Description File Format', 'application/vnd.cups-ppd', '.ppd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Adobe Shockwave Player', 'application/x-director', '.dir');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Adobe XML Data Package', 'application/vnd.adobe.xdp+xml', '.xdp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Adobe XML Forms Data Format', 'application/vnd.adobe.xfdf', '.xfdf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Advanced Audio Coding (AAC)', 'audio/x-aac', '.aac');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Ahead AIR Application', 'application/vnd.ahead.space', '.ahead');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('AirZip FileSECURE', 'application/vnd.airzip.filesecure.azf', '.azf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('AirZip FileSECURE', 'application/vnd.airzip.filesecure.azs', '.azs');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Amazon Kindle eBook format', 'application/vnd.amazon.ebook', '.azw');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('AmigaDE', 'application/vnd.amiga.ami', '.ami');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Android Package Archive', 'application/vnd.android.package-archive', '.apk');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('ANSER-WEB Terminal Client - Certificate Issue', 'application/vnd.anser-web-certificate-issue-initiation', '.cii');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('ANSER-WEB Terminal Client - Web Funds Transfer', 'application/vnd.anser-web-funds-transfer-initiation', '.fti');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Antix Game Player', 'application/vnd.antix.game-component', '.atx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Apple Installer Package', 'application/vnd.apple.installer+xml', '.mpkg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Applixware', 'application/applixware', '.aw');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Archipelago Lesson Player', 'application/vnd.hhe.lesson-player', '.les');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Arista Networks Software Image', 'application/vnd.aristanetworks.swi', '.swi');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Assembler Source File', 'text/x-asm', '.s');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Atom Publishing Protocol', 'application/atomcat+xml', '.atomcat');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Atom Publishing Protocol Service Document', 'application/atomsvc+xml', '.atomsvc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Atom Syndication Format', 'application/atom+xml', '.atom');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Attribute Certificate', 'application/pkix-attr-cert', '.ac');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Audio Interchange File Format', 'audio/x-aiff', '.aif');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Audio Video Interleave (AVI)', 'video/x-msvideo', '.avi');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Audiograph', 'application/vnd.audiograph', '.aep');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('AutoCAD DXF', 'image/vnd.dxf', '.dxf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Autodesk Design Web Format (DWF)', 'model/vnd.dwf', '.dwf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('BAS Partitur Format', 'text/plain-bas', '.par');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Binary CPIO Archive', 'application/x-bcpio', '.bcpio');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Binary Data', 'application/octet-stream', '.bin');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Bitmap Image File', 'image/bmp', '.bmp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('BitTorrent', 'application/x-bittorrent', '.torrent');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Blackberry COD File', 'application/vnd.rim.cod', '.cod');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Blueice Research Multipass', 'application/vnd.blueice.multipass', '.mpm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('BMI Drawing Data Interchange', 'application/vnd.bmi', '.bmi');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Bourne Shell Script', 'application/x-sh', '.sh');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('BTIF', 'image/prs.btif', '.btif');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('BusinessObjects', 'application/vnd.businessobjects', '.rep');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Bzip Archive', 'application/x-bzip', '.bz');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Bzip2 Archive', 'application/x-bzip2', '.bz2');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('C Shell Script', 'application/x-csh', '.csh');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('C Source File', 'text/x-c', '.c');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CambridgeSoft Chem Draw', 'application/vnd.chemdraw+xml', '.cdxml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Cascading Style Sheets (CSS)', 'text/css', '.css');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('ChemDraw eXchange file', 'chemical/x-cdx', '.cdx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Chemical Markup Language', 'chemical/x-cml', '.cml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Chemical Style Markup Language', 'chemical/x-csml', '.csml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CIM Database', 'application/vnd.contact.cmsg', '.cdbcmsg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Claymore Data Files', 'application/vnd.claymore', '.cla');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Clonk Game', 'application/vnd.clonk.c4group', '.c4g');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Close Captioning - Subtitle', 'image/vnd.dvb.subtitle', '.sub');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Cloud Data Management Interface (CDMI) - Capability', 'application/cdmi-capability', '.cdmia');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Cloud Data Management Interface (CDMI) - Contaimer', 'application/cdmi-container', '.cdmic');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Cloud Data Management Interface (CDMI) - Domain', 'application/cdmi-domain', '.cdmid');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Cloud Data Management Interface (CDMI) - Object', 'application/cdmi-object', '.cdmio');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Cloud Data Management Interface (CDMI) - Queue', 'application/cdmi-queue', '.cdmiq');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('ClueTrust CartoMobile - Config', 'application/vnd.cluetrust.cartomobile-config', '.c11amc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('ClueTrust CartoMobile - Config Package', 'application/vnd.cluetrust.cartomobile-config-pkg', '.c11amz');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CMU Image', 'image/x-cmu-raster', '.ras');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('COLLADA', 'model/vnd.collada+xml', '.dae');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Comma-Seperated Values', 'text/csv', '.csv');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Compact Pro', 'application/mac-compactpro', '.cpt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Compiled Wireless Markup Language (WMLC)', 'application/vnd.wap.wmlc', '.wmlc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Computer Graphics Metafile', 'image/cgm', '.cgm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CoolTalk', 'x-conference/x-cooltalk', '.ice');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Corel Metafile Exchange (CMX)', 'image/x-cmx', '.cmx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CorelXARA', 'application/vnd.xara', '.xar');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CosmoCaller', 'application/vnd.cosmocaller', '.cmc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CPIO Archive', 'application/x-cpio', '.cpio');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CrickSoftware - Clicker', 'application/vnd.crick.clicker', '.clkx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CrickSoftware - Clicker - Keyboard', 'application/vnd.crick.clicker.keyboard', '.clkk');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CrickSoftware - Clicker - Palette', 'application/vnd.crick.clicker.palette', '.clkp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CrickSoftware - Clicker - Template', 'application/vnd.crick.clicker.template', '.clkt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CrickSoftware - Clicker - Wordbank', 'application/vnd.crick.clicker.wordbank', '.clkw');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Critical Tools - PERT Chart EXPERT', 'application/vnd.criticaltools.wbs+xml', '.wbs');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CryptoNote', 'application/vnd.rig.cryptonote', '.cryptonote');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Crystallographic Interchange Format', 'chemical/x-cif', '.cif');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CrystalMaker Data Format', 'chemical/x-cmdf', '.cmdf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CU-SeeMe', 'application/cu-seeme', '.cu');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CU-Writer', 'application/prs.cww', '.cww');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Curl - Applet', 'text/vnd.curl', '.curl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Curl - Detached Applet', 'text/vnd.curl.dcurl', '.dcurl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Curl - Manifest File', 'text/vnd.curl.mcurl', '.mcurl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Curl - Source Code', 'text/vnd.curl.scurl', '.scurl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CURL Applet', 'application/vnd.curl.car', '.car');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CURL Applet', 'application/vnd.curl.pcurl', '.pcurl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('CustomMenu', 'application/vnd.yellowriver-custom-menu', '.cmp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Data Structure for the Security Suitability of Cryptographic Algorithms', 'application/dssc+der', '.dssc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Data Structure for the Security Suitability of Cryptographic Algorithms', 'application/dssc+xml', '.xdssc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Debian Package', 'application/x-debian-package', '.deb');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DECE Audio', 'audio/vnd.dece.audio', '.uva');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DECE Graphic', 'image/vnd.dece.graphic', '.uvi');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DECE High Definition Video', 'video/vnd.dece.hd', '.uvh');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DECE Mobile Video', 'video/vnd.dece.mobile', '.uvm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DECE MP4', 'video/vnd.uvvu.mp4', '.uvu');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DECE PD Video', 'video/vnd.dece.pd', '.uvp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DECE SD Video', 'video/vnd.dece.sd', '.uvs');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DECE Video', 'video/vnd.dece.video', '.uvv');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Device Independent File Format (DVI)', 'application/x-dvi', '.dvi');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Digital Siesmograph Networks - SEED Datafiles', 'application/vnd.fdsn.seed', '.seed');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Digital Talking Book', 'application/x-dtbook+xml', '.dtb');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Digital Talking Book - Resource File', 'application/x-dtbresource+xml', '.res');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Digital Video Broadcasting', 'application/vnd.dvb.ait', '.ait');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Digital Video Broadcasting', 'application/vnd.dvb.service', '.svc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Digital Winds Music', 'audio/vnd.digital-winds', '.eol');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DjVu', 'image/vnd.djvu', '.djvu');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Document Type Definition', 'application/xml-dtd', '.dtd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Dolby Meridian Lossless Packing', 'application/vnd.dolby.mlp', '.mlp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Doom Video Game', 'application/x-doom', '.wad');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DPGraph', 'application/vnd.dpgraph', '.dpg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DRA Audio', 'audio/vnd.dra', '.dra');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DreamFactory', 'application/vnd.dreamfactory', '.dfac');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DTS Audio', 'audio/vnd.dts', '.dts');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DTS High Definition Audio', 'audio/vnd.dts.hd', '.dtshd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DWG Drawing', 'image/vnd.dwg', '.dwg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('DynaGeo', 'application/vnd.dynageo', '.geo');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('ECMAScript', 'application/ecmascript', '.es');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('EcoWin Chart', 'application/vnd.ecowin.chart', '.mag');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('EDMICS 2000', 'image/vnd.fujixerox.edmics-mmr', '.mmr');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('EDMICS 2000', 'image/vnd.fujixerox.edmics-rlc', '.rlc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Efficient XML Interchange', 'application/exi', '.exi');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('EFI Proteus', 'application/vnd.proteus.magazine', '.mgz');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Electronic Publication', 'application/epub+zip', '.epub');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Email Message', 'message/rfc822', '.eml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Enliven Viewer', 'application/vnd.enliven', '.nml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Express by Infoseek', 'application/vnd.is-xpr', '.xpr');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('eXtended Image File Format (XIFF)', 'image/vnd.xiff', '.xif');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Extensible Forms Description Language', 'application/vnd.xfdl', '.xfdl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Extensible MultiModal Annotation', 'application/emma+xml', '.emma');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('EZPix Secure Photo Album', 'application/vnd.ezpix-album', '.ez2');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('EZPix Secure Photo Album', 'application/vnd.ezpix-package', '.ez3');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('FAST Search & Transfer ASA', 'image/vnd.fst', '.fst');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('FAST Search & Transfer ASA', 'video/vnd.fvt', '.fvt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('FastBid Sheet', 'image/vnd.fastbidsheet', '.fbs');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('FCS Express Layout Link', 'application/vnd.denovo.fcselayout-link', '.fe_launch');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Flash Video', 'video/x-f4v', '.f4v');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Flash Video', 'video/x-flv', '.flv');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('FlashPix', 'image/vnd.fpx', '.fpx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('FlashPix', 'image/vnd.net-fpx', '.npx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('FLEXSTOR', 'text/vnd.fmi.flexstor', '.flx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('FLI/FLC Animation Format', 'video/x-fli', '.fli');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('FluxTime Clip', 'application/vnd.fluxtime.clip', '.ftc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Forms Data Format', 'application/vnd.fdf', '.fdf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Fortran Source File', 'text/x-fortran', '.f');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('FrameMaker Interchange Format', 'application/vnd.mif', '.mif');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('FrameMaker Normal Format', 'application/vnd.framemaker', '.fm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('FreeHand MX', 'image/x-freehand', '.fh');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Friendly Software Corporation', 'application/vnd.fsc.weblaunch', '.fsc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Frogans Player', 'application/vnd.frogans.fnc', '.fnc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Frogans Player', 'application/vnd.frogans.ltf', '.ltf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Fujitsu - Xerox 2D CAD Data', 'application/vnd.fujixerox.ddd', '.ddd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Fujitsu - Xerox DocuWorks', 'application/vnd.fujixerox.docuworks', '.xdw');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Fujitsu - Xerox DocuWorks Binder', 'application/vnd.fujixerox.docuworks.binder', '.xbd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Fujitsu Oasys', 'application/vnd.fujitsu.oasys', '.oas');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Fujitsu Oasys', 'application/vnd.fujitsu.oasys2', '.oa2');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Fujitsu Oasys', 'application/vnd.fujitsu.oasys3', '.oa3');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Fujitsu Oasys', 'application/vnd.fujitsu.oasysgp', '.fg5');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Fujitsu Oasys', 'application/vnd.fujitsu.oasysprs', '.bh2');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('FutureSplash Animator', 'application/x-futuresplash', '.spl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('FuzzySheet', 'application/vnd.fuzzysheet', '.fzs');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('G3 Fax Image', 'image/g3fax', '.g3');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('GameMaker ActiveX', 'application/vnd.gmx', '.gmx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Gen-Trix Studio', 'model/vnd.gtw', '.gtw');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Genomatix Tuxedo Framework', 'application/vnd.genomatix.tuxedo', '.txd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('GeoGebra', 'application/vnd.geogebra.file', '.ggb');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('GeoGebra', 'application/vnd.geogebra.tool', '.ggt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Geometric Description Language (GDL)', 'model/vnd.gdl', '.gdl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('GeoMetry Explorer', 'application/vnd.geometry-explorer', '.gex');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('GEONExT and JSXGraph', 'application/vnd.geonext', '.gxt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('GeoplanW', 'application/vnd.geoplan', '.g2w');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('GeospacW', 'application/vnd.geospace', '.g3w');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Ghostscript Font', 'application/x-font-ghostscript', '.gsf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Glyph Bitmap Distribution Format', 'application/x-font-bdf', '.bdf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('GNU Tar Files', 'application/x-gtar', '.gtar');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('GNU Texinfo Document', 'application/x-texinfo', '.texinfo');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Gnumeric', 'application/x-gnumeric', '.gnumeric');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Google Earth - KML', 'application/vnd.google-earth.kml+xml', '.kml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Google Earth - Zipped KML', 'application/vnd.google-earth.kmz', '.kmz');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('GrafEq', 'application/vnd.grafeq', '.gqf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Graphics Interchange Format', 'image/gif', '.gif');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Graphviz', 'text/vnd.graphviz', '.gv');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Groove - Account', 'application/vnd.groove-account', '.gac');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Groove - Help', 'application/vnd.groove-help', '.ghf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Groove - Identity Message', 'application/vnd.groove-identity-message', '.gim');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Groove - Injector', 'application/vnd.groove-injector', '.grv');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Groove - Tool Message', 'application/vnd.groove-tool-message', '.gtm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Groove - Tool Template', 'application/vnd.groove-tool-template', '.tpl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Groove - Vcard', 'application/vnd.groove-vcard', '.vcg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('H.261', 'video/h261', '.h261');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('H.263', 'video/h263', '.h263');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('H.264', 'video/h264', '.h264');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Hewlett Packard Instant Delivery', 'application/vnd.hp-hpid', '.hpid');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Hewlett-Packard`s WebPrintSmart', 'application/vnd.hp-hps', '.hps');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Hierarchical Data Format', 'application/x-hdf', '.hdf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Hit`n`Mix', 'audio/vnd.rip', '.rip');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Homebanking Computer Interface (HBCI)', 'application/vnd.hbci', '.hbci');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('HP Indigo Digital Press - Job Layout Languate', 'application/vnd.hp-jlyt', '.jlt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('HP Printer Command Language', 'application/vnd.hp-pcl', '.pcl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('HP-GL/2 and HP RTL', 'application/vnd.hp-hpgl', '.hpgl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('HV Script', 'application/vnd.yamaha.hv-script', '.hvs');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('HV Voice Dictionary', 'application/vnd.yamaha.hv-dic', '.hvd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('HV Voice Parameter', 'application/vnd.yamaha.hv-voice', '.hvp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Hydrostatix Master Suite', 'application/vnd.hydrostatix.sof-data', '.sfd-hdstx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Hyperstudio', 'application/hyperstudio', '.stk');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Hypertext Application Language', 'application/vnd.hal+xml', '.hal');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('HyperText Markup Language (HTML)', 'text/html', '.html');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('IBM DB2 Rights Manager', 'application/vnd.ibm.rights-management', '.irm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('IBM Electronic Media Management System - Secure Container', 'application/vnd.ibm.secure-container', '.sc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('iCalendar', 'text/calendar', '.ics');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('ICC profile', 'application/vnd.iccprofile', '.icc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Icon Image', 'image/x-icon', '.ico');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('igLoader', 'application/vnd.igloader', '.igl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Image Exchange Format', 'image/ief', '.ief');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('ImmerVision PURE Players', 'application/vnd.immervision-ivp', '.ivp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('ImmerVision PURE Players', 'application/vnd.immervision-ivu', '.ivu');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('IMS Networks', 'application/reginfo+xml', '.rif');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('In3D - 3DML', 'text/vnd.in3d.3dml', '.3dml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('In3D - 3DML', 'text/vnd.in3d.spot', '.spot');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Initial Graphics Exchange Specification (IGES)', 'model/iges', '.igs');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Interactive Geometry Software', 'application/vnd.intergeo', '.i2g');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Interactive Geometry Software Cinderella', 'application/vnd.cinderella', '.cdy');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Intercon FormNet', 'application/vnd.intercon.formnet', '.xpw');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('International Society for Advancement of Cytometry', 'application/vnd.isac.fcs', '.fcs');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Internet Protocol Flow Information Export', 'application/ipfix', '.ipfix');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Internet Public Key Infrastructure - Certificate', 'application/pkix-cert', '.cer');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Internet Public Key Infrastructure - Certificate Management Protocole', 'application/pkixcmp', '.pki');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Internet Public Key Infrastructure - Certificate Revocation Lists', 'application/pkix-crl', '.crl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Internet Public Key Infrastructure - Certification Path', 'application/pkix-pkipath', '.pkipath');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('IOCOM Visimeet', 'application/vnd.insors.igm', '.igm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('IP Unplugged Roaming Client', 'application/vnd.ipunplugged.rcprofile', '.rcprofile');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('iRepository / Lucidoc Editor', 'application/vnd.irepository.package+xml', '.irp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('J2ME App Descriptor', 'text/vnd.sun.j2me.app-descriptor', '.jad');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Java Archive', 'application/java-archive', '.jar');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Java Bytecode File', 'application/java-vm', '.class');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Java Network Launching Protocol', 'application/x-java-jnlp-file', '.jnlp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Java Serialized Object', 'application/java-serialized-object', '.ser');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Java Source File', 'text/x-java-source,java', '.java');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('JavaScript', 'application/javascript', '.js');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('JavaScript Object Notation (JSON)', 'application/json', '.json');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Joda Archive', 'application/vnd.joost.joda-archive', '.joda');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('JPEG 2000 Compound Image File Format', 'video/jpm', '.jpm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('JPEG Image', 'image/jpeg', '.jpg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('JPEG Image', 'image/jpeg', '.jpeg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('JPGVideo', 'video/jpeg', '.jpgv');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Kahootz', 'application/vnd.kahootz', '.ktz');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Karaoke on Chipnuts Chipsets', 'application/vnd.chipnuts.karaoke-mmd', '.mmd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('KDE KOffice Office Suite - Karbon', 'application/vnd.kde.karbon', '.karbon');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('KDE KOffice Office Suite - KChart', 'application/vnd.kde.kchart', '.chrt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('KDE KOffice Office Suite - Kformula', 'application/vnd.kde.kformula', '.kfo');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('KDE KOffice Office Suite - Kivio', 'application/vnd.kde.kivio', '.flw');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('KDE KOffice Office Suite - Kontour', 'application/vnd.kde.kontour', '.kon');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('KDE KOffice Office Suite - Kpresenter', 'application/vnd.kde.kpresenter', '.kpr');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('KDE KOffice Office Suite - Kspread', 'application/vnd.kde.kspread', '.ksp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('KDE KOffice Office Suite - Kword', 'application/vnd.kde.kword', '.kwd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Kenamea App', 'application/vnd.kenameaapp', '.htke');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Kidspiration', 'application/vnd.kidspiration', '.kia');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Kinar Applications', 'application/vnd.kinar', '.kne');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Kodak Storyshare', 'application/vnd.kodak-descriptor', '.sse');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Laser App Enterprise', 'application/vnd.las.las+xml', '.lasxml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('LaTeX', 'application/x-latex', '.latex');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Life Balance - Desktop Edition', 'application/vnd.llamagraphics.life-balance.desktop', '.lbd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Life Balance - Exchange Format', 'application/vnd.llamagraphics.life-balance.exchange+xml', '.lbe');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Lightspeed Audio Lab', 'application/vnd.jam', '.jam');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Lotus 1-2-3', 'application/vnd.lotus-1-2-3', '.123');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Lotus Approach', 'application/vnd.lotus-approach', '.apr');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Lotus Freelance', 'application/vnd.lotus-freelance', '.pre');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Lotus Notes', 'application/vnd.lotus-notes', '.nsf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Lotus Organizer', 'application/vnd.lotus-organizer', '.org');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Lotus Screencam', 'application/vnd.lotus-screencam', '.scm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Lotus Wordpro', 'application/vnd.lotus-wordpro', '.lwp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Lucent Voice', 'audio/vnd.lucent.voice', '.lvp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('M3U (Multimedia Playlist)', 'audio/x-mpegurl', '.m3u');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('M4v', 'video/x-m4v', '.m4v');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Macintosh BinHex 4.0', 'application/mac-binhex40', '.hqx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MacPorts Port System', 'application/vnd.macports.portpkg', '.portpkg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MapGuide DBXML', 'application/vnd.osgeo.mapguide.package', '.mgp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MARC Formats', 'application/marc', '.mrc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MARC21 XML Schema', 'application/marcxml+xml', '.mrcx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Material Exchange Format', 'application/mxf', '.mxf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mathematica Notebook Player', 'application/vnd.wolfram.player', '.nbp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mathematica Notebooks', 'application/mathematica', '.ma');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mathematical Markup Language', 'application/mathml+xml', '.mathml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mbox database files', 'application/mbox', '.mbox');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MedCalc', 'application/vnd.medcalcdata', '.mc1');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Media Server Control Markup Language', 'application/mediaservercontrol+xml', '.mscml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MediaRemote', 'application/vnd.mediastation.cdkey', '.cdkey');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Medical Waveform Encoding Format', 'application/vnd.mfer', '.mwf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Melody Format for Mobile Platform', 'application/vnd.mfmp', '.mfm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mesh Data Type', 'model/mesh', '.msh');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Metadata Authority Description Schema', 'application/mads+xml', '.mads');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Metadata Encoding and Transmission Standard', 'application/mets+xml', '.mets');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Metadata Object Description Schema', 'application/mods+xml', '.mods');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Metalink', 'application/metalink4+xml', '.meta4');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Micosoft PowerPoint - Macro-Enabled Template File', 'application/vnd.ms-powerpoint.template.macroenabled.12', '.potm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Micosoft Word - Macro-Enabled Document', 'application/vnd.ms-word.document.macroenabled.12', '.docm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Micosoft Word - Macro-Enabled Template', 'application/vnd.ms-word.template.macroenabled.12', '.dotm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Micro CADAM Helix D&D', 'application/vnd.mcd', '.mcd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Micrografx', 'application/vnd.micrografx.flo', '.flo');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Micrografx iGrafx Professional', 'application/vnd.micrografx.igx', '.igx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MICROSEC e-Szign¢', 'application/vnd.eszigno3+xml', '.es3');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Access', 'application/x-msaccess', '.mdb');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Advanced Systems Format (ASF)', 'video/x-ms-asf', '.asf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Application', 'application/x-msdownload', '.exe');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Artgalry', 'application/vnd.ms-artgalry', '.cil');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Cabinet File', 'application/vnd.ms-cab-compressed', '.cab');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Class Server', 'application/vnd.ms-ims', '.ims');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft ClickOnce', 'application/x-ms-application', '.application');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Clipboard Clip', 'application/x-msclip', '.clp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Document Imaging Format', 'image/vnd.ms-modi', '.mdi');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Embedded OpenType', 'application/vnd.ms-fontobject', '.eot');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Excel', 'application/vnd.ms-excel', '.xls');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Excel - Add-In File', 'application/vnd.ms-excel.addin.macroenabled.12', '.xlam');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Excel - Binary Workbook', 'application/vnd.ms-excel.sheet.binary.macroenabled.12', '.xlsb');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Excel - Macro-Enabled Template File', 'application/vnd.ms-excel.template.macroenabled.12', '.xltm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Excel - Macro-Enabled Workbook', 'application/vnd.ms-excel.sheet.macroenabled.12', '.xlsm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Html Help File', 'application/vnd.ms-htmlhelp', '.chm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Information Card', 'application/x-mscardfile', '.crd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Learning Resource Module', 'application/vnd.ms-lrm', '.lrm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft MediaView', 'application/x-msmediaview', '.mvb');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Money', 'application/x-msmoney', '.mny');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Office - OOXML - Presentation', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', '.pptx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Office - OOXML - Presentation (Slide)', 'application/vnd.openxmlformats-officedocument.presentationml.slide', '.sldx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Office - OOXML - Presentation (Slideshow)', 'application/vnd.openxmlformats-officedocument.presentationml.slideshow', '.ppsx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Office - OOXML - Presentation Template', 'application/vnd.openxmlformats-officedocument.presentationml.template', '.potx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Office - OOXML - Spreadsheet', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', '.xlsx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Office - OOXML - Spreadsheet Teplate', 'application/vnd.openxmlformats-officedocument.spreadsheetml.template', '.xltx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Office - OOXML - Word Document', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', '.docx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Office - OOXML - Word Document Template', 'application/vnd.openxmlformats-officedocument.wordprocessingml.template', '.dotx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Office Binder', 'application/x-msbinder', '.obd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Office System Release Theme', 'application/vnd.ms-officetheme', '.thmx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft OneNote', 'application/onenote', '.onetoc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft PlayReady Ecosystem', 'audio/vnd.ms-playready.media.pya', '.pya');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft PlayReady Ecosystem Video', 'video/vnd.ms-playready.media.pyv', '.pyv');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft PowerPoint', 'application/vnd.ms-powerpoint', '.ppt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft PowerPoint - Add-in file', 'application/vnd.ms-powerpoint.addin.macroenabled.12', '.ppam');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft PowerPoint - Macro-Enabled Open XML Slide', 'application/vnd.ms-powerpoint.slide.macroenabled.12', '.sldm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft PowerPoint - Macro-Enabled Presentation File', 'application/vnd.ms-powerpoint.presentation.macroenabled.12', '.pptm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft PowerPoint - Macro-Enabled Slide Show File', 'application/vnd.ms-powerpoint.slideshow.macroenabled.12', '.ppsm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Project', 'application/vnd.ms-project', '.mpp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Publisher', 'application/x-mspublisher', '.pub');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Schedule+', 'application/x-msschedule', '.scd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Silverlight', 'application/x-silverlight-app', '.xap');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Trust UI Provider - Certificate Trust Link', 'application/vnd.ms-pki.stl', '.stl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Trust UI Provider - Security Catalog', 'application/vnd.ms-pki.seccat', '.cat');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Visio', 'application/vnd.visio', '.vsd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Windows Media', 'video/x-ms-wm', '.wm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Windows Media Audio', 'audio/x-ms-wma', '.wma');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Windows Media Audio Redirector', 'audio/x-ms-wax', '.wax');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Windows Media Audio/Video Playlist', 'video/x-ms-wmx', '.wmx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Windows Media Player Download Package', 'application/x-ms-wmd', '.wmd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Windows Media Player Playlist', 'application/vnd.ms-wpl', '.wpl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Windows Media Player Skin Package', 'application/x-ms-wmz', '.wmz');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Windows Media Video', 'video/x-ms-wmv', '.wmv');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Windows Media Video Playlist', 'video/x-ms-wvx', '.wvx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Windows Metafile', 'application/x-msmetafile', '.wmf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Windows Terminal Services', 'application/x-msterminal', '.trm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Word', 'application/msword', '.doc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Wordpad', 'application/x-mswrite', '.wri');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft Works', 'application/vnd.ms-works', '.wps');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft XAML Browser Application', 'application/x-ms-xbap', '.xbap');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Microsoft XML Paper Specification', 'application/vnd.ms-xpsdocument', '.xps');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MIDI - Musical Instrument Digital Interface', 'audio/midi', '.mid');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MiniPay', 'application/vnd.ibm.minipay', '.mpy');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MO:DCA-P', 'application/vnd.ibm.modcap', '.afp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mobile Information Device Profile', 'application/vnd.jcp.javame.midlet-rms', '.rms');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MobileTV', 'application/vnd.tmobile-livetv', '.tmo');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mobipocket', 'application/x-mobipocket-ebook', '.prc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mobius Management Systems - Basket file', 'application/vnd.mobius.mbk', '.mbk');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mobius Management Systems - Distribution Database', 'application/vnd.mobius.dis', '.dis');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mobius Management Systems - Policy Definition Language File', 'application/vnd.mobius.plc', '.plc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mobius Management Systems - Query File', 'application/vnd.mobius.mqy', '.mqy');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mobius Management Systems - Script Language', 'application/vnd.mobius.msl', '.msl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mobius Management Systems - Topic Index File', 'application/vnd.mobius.txf', '.txf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mobius Management Systems - UniversalArchive', 'application/vnd.mobius.daf', '.daf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('mod_fly / fly.cgi', 'text/vnd.fly', '.fly');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mophun Certificate', 'application/vnd.mophun.certificate', '.mpc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Mophun VM', 'application/vnd.mophun.application', '.mpn');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Motion JPEG 2000', 'video/mj2', '.mj2');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MPEG Audio', 'audio/mpeg', '.mpga');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MPEG Url', 'video/vnd.mpegurl', '.mxu');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MPEG Video', 'video/mpeg', '.mpeg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MPEG-21', 'application/mp21', '.m21');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MPEG-4 Audio', 'audio/mp4', '.mp4a');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MPEG4', 'application/mp4', '.mp4');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Multimedia Playlist Unicode', 'application/vnd.apple.mpegurl', '.m3u8');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MUsical Score Interpreted Code Invented for the ASCII designation of Notation', 'application/vnd.musician', '.mus');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Muvee Automatic Video Editing', 'application/vnd.muvee.style', '.msty');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('MXML', 'application/xv+xml', '.mxml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('N-Gage Game Data', 'application/vnd.nokia.n-gage.data', '.ngdat');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('N-Gage Game Installer', 'application/vnd.nokia.n-gage.symbian.install', '.n-gage');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Navigation Control file for XML (for ePub)', 'application/x-dtbncx+xml', '.ncx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Network Common Data Form (NetCDF)', 'application/x-netcdf', '.nc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('neuroLanguage', 'application/vnd.neurolanguage.nlu', '.nlu');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('New Moon Liftoff/DNA', 'application/vnd.dna', '.dna');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('NobleNet Directory', 'application/vnd.noblenet-directory', '.nnd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('NobleNet Sealer', 'application/vnd.noblenet-sealer', '.nns');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('NobleNet Web', 'application/vnd.noblenet-web', '.nnw');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Nokia Radio Application - Preset', 'application/vnd.nokia.radio-preset', '.rpst');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Nokia Radio Application - Preset', 'application/vnd.nokia.radio-presets', '.rpss');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Notation3', 'text/n3', '.n3');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Novadigm`s RADIA and EDM products', 'application/vnd.novadigm.edm', '.edm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Novadigm`s RADIA and EDM products', 'application/vnd.novadigm.edx', '.edx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Novadigm`s RADIA and EDM products', 'application/vnd.novadigm.ext', '.ext');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('NpGraphIt', 'application/vnd.flographit', '.gph');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Nuera ECELP 4800', 'audio/vnd.nuera.ecelp4800', '.ecelp4800');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Nuera ECELP 7470', 'audio/vnd.nuera.ecelp7470', '.ecelp7470');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Nuera ECELP 9600', 'audio/vnd.nuera.ecelp9600', '.ecelp9600');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Office Document Architecture', 'application/oda', '.oda');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Ogg', 'application/ogg', '.ogx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Ogg Audio', 'audio/ogg', '.oga');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Ogg Video', 'video/ogg', '.ogv');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OMA Download Agents', 'application/vnd.oma.dd2+xml', '.dd2');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Open Document Text Web', 'application/vnd.oasis.opendocument.text-web', '.oth');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Open eBook Publication Structure', 'application/oebps-package+xml', '.opf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Open Financial Exchange', 'application/vnd.intu.qbo', '.qbo');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Open Office Extension', 'application/vnd.openofficeorg.extension', '.oxt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Open Score Format', 'application/vnd.yamaha.openscoreformat', '.osf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Open Web Media Project - Audio', 'audio/webm', '.weba');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Open Web Media Project - Video', 'video/webm', '.webm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Chart', 'application/vnd.oasis.opendocument.chart', '.odc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Chart Template', 'application/vnd.oasis.opendocument.chart-template', '.otc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Database', 'application/vnd.oasis.opendocument.database', '.odb');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Formula', 'application/vnd.oasis.opendocument.formula', '.odf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Formula Template', 'application/vnd.oasis.opendocument.formula-template', '.odft');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Graphics', 'application/vnd.oasis.opendocument.graphics', '.odg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Graphics Template', 'application/vnd.oasis.opendocument.graphics-template', '.otg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Image', 'application/vnd.oasis.opendocument.image', '.odi');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Image Template', 'application/vnd.oasis.opendocument.image-template', '.oti');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Presentation', 'application/vnd.oasis.opendocument.presentation', '.odp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Presentation Template', 'application/vnd.oasis.opendocument.presentation-template', '.otp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Spreadsheet', 'application/vnd.oasis.opendocument.spreadsheet', '.ods');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Spreadsheet Template', 'application/vnd.oasis.opendocument.spreadsheet-template', '.ots');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Text', 'application/vnd.oasis.opendocument.text', '.odt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Text Master', 'application/vnd.oasis.opendocument.text-master', '.odm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenDocument Text Template', 'application/vnd.oasis.opendocument.text-template', '.ott');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenGL Textures (KTX)', 'image/ktx', '.ktx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenOffice - Calc (Spreadsheet)', 'application/vnd.sun.xml.calc', '.sxc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenOffice - Calc Template (Spreadsheet)', 'application/vnd.sun.xml.calc.template', '.stc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenOffice - Draw (Graphics)', 'application/vnd.sun.xml.draw', '.sxd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenOffice - Draw Template (Graphics)', 'application/vnd.sun.xml.draw.template', '.std');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenOffice - Impress (Presentation)', 'application/vnd.sun.xml.impress', '.sxi');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenOffice - Impress Template (Presentation)', 'application/vnd.sun.xml.impress.template', '.sti');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenOffice - Math (Formula)', 'application/vnd.sun.xml.math', '.sxm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenOffice - Writer (Text - HTML)', 'application/vnd.sun.xml.writer', '.sxw');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenOffice - Writer (Text - HTML)', 'application/vnd.sun.xml.writer.global', '.sxg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenOffice - Writer Template (Text - HTML)', 'application/vnd.sun.xml.writer.template', '.stw');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OpenType Font File', 'application/x-font-otf', '.otf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OSFPVG', 'application/vnd.yamaha.openscoreformat.osfpvg+xml', '.osfpvg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('OSGi Deployment Package', 'application/vnd.osgi.dp', '.dp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PalmOS Data', 'application/vnd.palm', '.pdb');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Pascal Source File', 'text/x-pascal', '.p');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PawaaFILE', 'application/vnd.pawaafile', '.paw');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PCL 6 Enhanced (Formely PCL XL)', 'application/vnd.hp-pclxl', '.pclxl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Pcsel eFIF File', 'application/vnd.picsel', '.efif');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PCX Image', 'image/x-pcx', '.pcx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Photoshop Document', 'image/vnd.adobe.photoshop', '.psd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PICSRules', 'application/pics-rules', '.prf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PICT Image', 'image/x-pict', '.pic');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('pIRCh', 'application/x-chat', '.chat');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PKCS #10 - Certification Request Standard', 'application/pkcs10', '.p10');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PKCS #12 - Personal Information Exchange Syntax Standard', 'application/x-pkcs12', '.p12');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PKCS #7 - Cryptographic Message Syntax Standard', 'application/pkcs7-mime', '.p7m');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PKCS #7 - Cryptographic Message Syntax Standard', 'application/pkcs7-signature', '.p7s');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)', 'application/x-pkcs7-certreqresp', '.p7r');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PKCS #7 - Cryptographic Message Syntax Standard (Certificates)', 'application/x-pkcs7-certificates', '.p7b');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PKCS #8 - Private-Key Information Syntax Standard', 'application/pkcs8', '.p8');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PocketLearn Viewers', 'application/vnd.pocketlearn', '.plf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Portable Anymap Image', 'image/x-portable-anymap', '.pnm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Portable Bitmap Format', 'image/x-portable-bitmap', '.pbm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Portable Compiled Format', 'application/x-font-pcf', '.pcf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Portable Font Resource', 'application/font-tdpfr', '.pfr');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Portable Game Notation (Chess Games)', 'application/x-chess-pgn', '.pgn');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Portable Graymap Format', 'image/x-portable-graymap', '.pgm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Portable Network Graphics (PNG)', 'image/png', '.png');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Portable Pixmap Format', 'image/x-portable-pixmap', '.ppm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Portable Symmetric Key Container', 'application/pskc+xml', '.pskcxml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PosML', 'application/vnd.ctc-posml', '.pml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PostScript', 'application/postscript', '.ai');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PostScript Fonts', 'application/x-font-type1', '.pfa');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PowerBuilder', 'application/vnd.powerbuilder6', '.pbd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Pretty Good Privacy - Signature', 'application/pgp-signature', '.pgp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Preview Systems ZipLock/VBox', 'application/vnd.previewsystems.box', '.box');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Princeton Video Image', 'application/vnd.pvi.ptid1', '.ptid');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Pronunciation Lexicon Specification', 'application/pls+xml', '.pls');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Proprietary P&G Standard Reporting System', 'application/vnd.pg.format', '.str');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Proprietary P&G Standard Reporting System', 'application/vnd.pg.osasli', '.ei6');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PRS Lines Tag', 'text/prs.lines.tag', '.dsc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PSF Fonts', 'application/x-font-linux-psf', '.psf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('PubliShare Objects', 'application/vnd.publishare-delta-tree', '.qps');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Qualcomm`s Plaza Mobile Internet', 'application/vnd.pmi.widget', '.wg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('QuarkXpress', 'application/vnd.quark.quarkxpress', '.qxd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('QUASS Stream Player', 'application/vnd.epson.esf', '.esf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('QUASS Stream Player', 'application/vnd.epson.msf', '.msf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('QUASS Stream Player', 'application/vnd.epson.ssf', '.ssf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('QuickAnime Player', 'application/vnd.epson.quickanime', '.qam');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Quicken', 'application/vnd.intu.qfx', '.qfx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Quicktime Video', 'video/quicktime', '.qt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('RAR Archive', 'application/x-rar-compressed', '.rar');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Real Audio Sound', 'audio/x-pn-realaudio', '.ram');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Real Audio Sound', 'audio/x-pn-realaudio-plugin', '.rmp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Really Simple Discovery', 'application/rsd+xml', '.rsd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('RealMedia', 'application/vnd.rn-realmedia', '.rm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('RealVNC', 'application/vnd.realvnc.bed', '.bed');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Recordare Applications', 'application/vnd.recordare.musicxml', '.mxl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Recordare Applications', 'application/vnd.recordare.musicxml+xml', '.musicxml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Relax NG Compact Syntax', 'application/relax-ng-compact-syntax', '.rnc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('RemoteDocs R-Viewer', 'application/vnd.data-vision.rdz', '.rdz');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Resource Description Framework', 'application/rdf+xml', '.rdf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('RetroPlatform Player', 'application/vnd.cloanto.rp9', '.rp9');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('RhymBox', 'application/vnd.jisp', '.jisp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Rich Text Format', 'application/rtf', '.rtf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Rich Text Format (RTF)', 'text/richtext', '.rtx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('ROUTE 66 Location Based Services', 'application/vnd.route66.link66+xml', '.link66');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('RSS - Really Simple Syndication', 'application/rss+xml', '.rss');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('S Hexdump Format', 'application/shf+xml', '.shf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SailingTracker', 'application/vnd.sailingtracker.track', '.st');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Scalable Vector Graphics (SVG)', 'image/svg+xml', '.svg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('ScheduleUs', 'application/vnd.sus-calendar', '.sus');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Search/Retrieve via URL Response Format', 'application/sru+xml', '.sru');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Secure Electronic Transaction - Payment', 'application/set-payment-initiation', '.setpay');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Secure Electronic Transaction - Registration', 'application/set-registration-initiation', '.setreg');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Secured eMail', 'application/vnd.sema', '.sema');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Secured eMail', 'application/vnd.semd', '.semd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Secured eMail', 'application/vnd.semf', '.semf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SeeMail', 'application/vnd.seemail', '.see');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Server Normal Format', 'application/x-font-snf', '.snf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Server-Based Certificate Validation Protocol - Validation Policies - Request', 'application/scvp-vp-request', '.spq');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Server-Based Certificate Validation Protocol - Validation Policies - Response', 'application/scvp-vp-response', '.spp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Server-Based Certificate Validation Protocol - Validation Request', 'application/scvp-cv-request', '.scq');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Server-Based Certificate Validation Protocol - Validation Response', 'application/scvp-cv-response', '.scs');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Session Description Protocol', 'application/sdp', '.sdp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Setext', 'text/x-setext', '.etx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SGI Movie', 'video/x-sgi-movie', '.movie');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Shana Informed Filler', 'application/vnd.shana.informed.formdata', '.ifm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Shana Informed Filler', 'application/vnd.shana.informed.formtemplate', '.itp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Shana Informed Filler', 'application/vnd.shana.informed.interchange', '.iif');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Shana Informed Filler', 'application/vnd.shana.informed.package', '.ipk');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Sharing Transaction Fraud Data', 'application/thraud+xml', '.tfi');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Shell Archive', 'application/x-shar', '.shar');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Silicon Graphics RGB Bitmap', 'image/x-rgb', '.rgb');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SimpleAnimeLite Player', 'application/vnd.epson.salt', '.slt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Simply Accounting', 'application/vnd.accpac.simply.aso', '.aso');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Simply Accounting - Data Import', 'application/vnd.accpac.simply.imp', '.imp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SimTech MindMapper', 'application/vnd.simtech-mindmapper', '.twd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Sixth Floor Media - CommonSpace', 'application/vnd.commonspace', '.csp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SMAF Audio', 'application/vnd.yamaha.smaf-audio', '.saf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SMAF File', 'application/vnd.smaf', '.mmf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SMAF Phrase', 'application/vnd.yamaha.smaf-phrase', '.spf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SMART Technologies Apps', 'application/vnd.smart.teacher', '.teacher');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SourceView Document', 'application/vnd.svd', '.svd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SPARQL - Query', 'application/sparql-query', '.rq');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SPARQL - Results', 'application/sparql-results+xml', '.srx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Speech Recognition Grammar Specification', 'application/srgs', '.gram');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Speech Recognition Grammar Specification - XML', 'application/srgs+xml', '.grxml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Speech Synthesis Markup Language', 'application/ssml+xml', '.ssml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SSEYO Koan Play File', 'application/vnd.koan', '.skp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Standard Generalized Markup Language (SGML)', 'text/sgml', '.sgml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('StarOffice - Calc', 'application/vnd.stardivision.calc', '.sdc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('StarOffice - Draw', 'application/vnd.stardivision.draw', '.sda');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('StarOffice - Impress', 'application/vnd.stardivision.impress', '.sdd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('StarOffice - Math', 'application/vnd.stardivision.math', '.smf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('StarOffice - Writer', 'application/vnd.stardivision.writer', '.sdw');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('StarOffice - Writer (Global)', 'application/vnd.stardivision.writer-global', '.sgl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('StepMania', 'application/vnd.stepmania.stepchart', '.sm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Stuffit Archive', 'application/x-stuffit', '.sit');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Stuffit Archive', 'application/x-stuffitx', '.sitx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SudokuMagic', 'application/vnd.solent.sdkm+xml', '.sdkm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Sugar Linux Application Bundle', 'application/vnd.olpc-sugar', '.xo');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Sun Audio - Au file format', 'audio/basic', '.au');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SundaHus WQ', 'application/vnd.wqd', '.wqd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Symbian Install Package', 'application/vnd.symbian.install', '.sis');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Synchronized Multimedia Integration Language', 'application/smil+xml', '.smi');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SyncML', 'application/vnd.syncml+xml', '.xsm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SyncML - Device Management', 'application/vnd.syncml.dm+wbxml', '.bdm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('SyncML - Device Management', 'application/vnd.syncml.dm+xml', '.xdm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('System V Release 4 CPIO Archive', 'application/x-sv4cpio', '.sv4cpio');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('System V Release 4 CPIO Checksum Data', 'application/x-sv4crc', '.sv4crc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Systems Biology Markup Language', 'application/sbml+xml', '.sbml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Tab Seperated Values', 'text/tab-separated-values', '.tsv');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Tagged Image File Format', 'image/tiff', '.tiff');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Tao Intent', 'application/vnd.tao.intent-module-archive', '.tao');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Tar File (Tape Archive)', 'application/x-tar', '.tar');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Tcl Script', 'application/x-tcl', '.tcl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('TeX', 'application/x-tex', '.tex');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('TeX Font Metric', 'application/x-tex-tfm', '.tfm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Text Encoding and Interchange', 'application/tei+xml', '.tei');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Text File', 'text/plain', '.txt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('TIBCO Spotfire', 'application/vnd.spotfire.dxp', '.dxp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('TIBCO Spotfire', 'application/vnd.spotfire.sfs', '.sfs');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Time Stamped Data Envelope', 'application/timestamped-data', '.tsd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('TRI Systems Config', 'application/vnd.trid.tpt', '.tpt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Triscape Map Explorer', 'application/vnd.triscape.mxs', '.mxs');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('troff', 'text/troff', '.t');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('True BASIC', 'application/vnd.trueapp', '.tra');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('TrueType Font', 'application/x-font-ttf', '.ttf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Turtle (Terse RDF Triple Language)', 'text/turtle', '.ttl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('UMAJIN', 'application/vnd.umajin', '.umj');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Unique Object Markup Language', 'application/vnd.uoml+xml', '.uoml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Unity 3d', 'application/vnd.unity', '.unityweb');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Universal Forms Description Language', 'application/vnd.ufdl', '.ufd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('URI Resolution Services', 'text/uri-list', '.uri');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('User Interface Quartz - Theme (Symbian)', 'application/vnd.uiq.theme', '.utz');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Ustar (Uniform Standard Tape Archive)', 'application/x-ustar', '.ustar');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('UUEncode', 'text/x-uuencode', '.uu');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('vCalendar', 'text/x-vcalendar', '.vcs');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('vCard', 'text/x-vcard', '.vcf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Video CD', 'application/x-cdlink', '.vcd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Viewport+', 'application/vnd.vsf', '.vsf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Virtual Reality Modeling Language', 'model/vrml', '.wrl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('VirtualCatalog', 'application/vnd.vcx', '.vcx');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Virtue MTS', 'model/vnd.mts', '.mts');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Virtue VTU', 'model/vnd.vtu', '.vtu');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Visionary', 'application/vnd.visionary', '.vis');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Vivo', 'video/vnd.vivo', '.viv');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Voice Browser Call Control', 'application/ccxml+xml,', '.ccxml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('VoiceXML', 'application/voicexml+xml', '.vxml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('WAIS Source', 'application/x-wais-source', '.src');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('WAP Binary XML (WBXML)', 'application/vnd.wap.wbxml', '.wbxml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('WAP Bitamp (WBMP)', 'image/vnd.wap.wbmp', '.wbmp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Waveform Audio File Format (WAV)', 'audio/x-wav', '.wav');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Web Distributed Authoring and Versioning', 'application/davmount+xml', '.davmount');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Web Open Font Format', 'application/x-font-woff', '.woff');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Web Services Policy', 'application/wspolicy+xml', '.wspolicy');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('WebP Image', 'image/webp', '.webp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('WebTurbo', 'application/vnd.webturbo', '.wtb');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Widget Packaging and XML Configuration', 'application/widget', '.wgt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('WinHelp', 'application/winhlp', '.hlp');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Wireless Markup Language (WML)', 'text/vnd.wap.wml', '.wml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Wireless Markup Language Script (WMLScript)', 'text/vnd.wap.wmlscript', '.wmls');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('WMLScript', 'application/vnd.wap.wmlscriptc', '.wmlsc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Wordperfect', 'application/vnd.wordperfect', '.wpd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Worldtalk', 'application/vnd.wt.stf', '.stf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('WSDL - Web Services Description Language', 'application/wsdl+xml', '.wsdl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('X BitMap', 'image/x-xbitmap', '.xbm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('X PixMap', 'image/x-xpixmap', '.xpm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('X Window Dump', 'image/x-xwindowdump', '.xwd');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('X.509 Certificate', 'application/x-x509-ca-cert', '.der');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Xfig', 'application/x-xfig', '.fig');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('XHTML - The Extensible HyperText Markup Language', 'application/xhtml+xml', '.xhtml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('XML - Extensible Markup Language', 'application/xml', '.xml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('XML Configuration Access Protocol - XCAP Diff', 'application/xcap-diff+xml', '.xdf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('XML Encryption Syntax and Processing', 'application/xenc+xml', '.xenc');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('XML Patch Framework', 'application/patch-ops-error+xml', '.xer');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('XML Resource Lists', 'application/resource-lists+xml', '.rl');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('XML Resource Lists', 'application/rls-services+xml', '.rs');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('XML Resource Lists Diff', 'application/resource-lists-diff+xml', '.rld');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('XML Transformations', 'application/xslt+xml', '.xslt');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('XML-Binary Optimized Packaging', 'application/xop+xml', '.xop');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('XPInstall - Mozilla', 'application/x-xpinstall', '.xpi');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('XSPF - XML Shareable Playlist Format', 'application/xspf+xml', '.xspf');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('XUL - XML User Interface Language', 'application/vnd.mozilla.xul+xml', '.xul');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('XYZ File Format', 'chemical/x-xyz', '.xyz');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('YAML Ain`t Markup Language / Yet Another Markup Language', 'text/yaml', '.yaml');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('YANG Data Modeling Language', 'application/yang', '.yang');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('YIN (YANG - XML)', 'application/yin+xml', '.yin');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Z.U.L. Geometry', 'application/vnd.zul', '.zir');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Zip Archive', 'application/zip', '.zip');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('ZVUE Media Manager', 'application/vnd.handheld-entertainment+xml', '.zmm');
INSERT INTO [dbo].[MIMEType] ([Name],[MIMEType],[Extension]) VALUES ('Zzazz Deck', 'application/vnd.zzazz.deck+xml', '.zaz');

GO